//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvoNUnit.Test.Test.Inputs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsBetweenTest
    {
        public Nullable<int> value { get; set; }
        public Nullable<int> lower_bound { get; set; }
        public Nullable<int> upper_bound { get; set; }
        public Nullable<bool> expected { get; set; }
        public int id { get; set; }
    }
}
