//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvoNUnit.Test.Test.Inputs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NUnitEntities1 : DbContext
    {
        public NUnitEntities1()
            : base("name=NUnitEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IsBetweenTest> IsBetweenTest { get; set; }
        public virtual DbSet<IsExactTest> IsExactTest { get; set; }
        public virtual DbSet<IsMultipleTest> IsMultipleTest { get; set; }
    }
}
